name: medialert
description: Aplicación de alertas de medicamentos para adultos mayores.
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  cupertino_icons: ^1.0.2
  uuid: ^4.3.3 
  shared_preferences: ^2.2.2
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.0
  flutterfire_cli: ^1.2.0
  google_fonts: ^6.1.0
  permission_handler: ^11.3.1
  firebase_messaging: ^14.7.11


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_icons:
  android: true
  ios: false
  image_path: "assets/logoApp.png"    