// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOZgSHDzSF53dndmgaK6O5HpBUU5ct2dU',
    appId: '1:723649721868:web:4df8624cbcacf7e757a029',
    messagingSenderId: '723649721868',
    projectId: 'medialertapp-a9560',
    authDomain: 'medialertapp-a9560.firebaseapp.com',
    storageBucket: 'medialertapp-a9560.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEfm1PC3g3noNrw97b64OQHLKYfNTpyPI',
    appId: '1:723649721868:android:e52fde96c04b4a4857a029',
    messagingSenderId: '723649721868',
    projectId: 'medialertapp-a9560',
    storageBucket: 'medialertapp-a9560.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBV7_fWkjte17hqgPdDZfdAMT99mLZjQ7k',
    appId: '1:723649721868:ios:69e3c0b3281a7b1857a029',
    messagingSenderId: '723649721868',
    projectId: 'medialertapp-a9560',
    storageBucket: 'medialertapp-a9560.firebasestorage.app',
    iosBundleId: 'com.example.medialert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOZgSHDzSF53dndmgaK6O5HpBUU5ct2dU',
    appId: '1:723649721868:web:47d00f0dbfd687cf57a029',
    messagingSenderId: '723649721868',
    projectId: 'medialertapp-a9560',
    authDomain: 'medialertapp-a9560.firebaseapp.com',
    storageBucket: 'medialertapp-a9560.firebasestorage.app',
  );
}
